spring.datasource.url=jdbc:postgresql://localhost:5432/challenge
spring.datasource.username=clara
spring.datasource.password=clarapasswd
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size = 500MB
spring.servlet.multipart.max-request-size = 500MB