spring.datasource.url=jdbc:postgresql://postgresql:5432/challenge
spring.datasource.username=clara
spring.datasource.password=clarapasswd
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
minio.url=http://minio:9000
minio.accessKey=GbfFgGs2aj1wp6eGzQFS
minio.secretKey=VYw0a0qLqEyOMfXgCPf4bDHppdjOvpFIhrS8vzel
spring.servlet.multipart.max-file-size = 500MB
spring.servlet.multipart.max-request-size = 500MB